name: retirodelrocioapp
description: "Retiro Del Rocio — luxury hotel and retreat in Jos, Plateau State."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.4


dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.3

  # Navigation
  go_router: ^17.3.0

  # Networking
  dio: ^5.10.0
  pretty_dio_logger: ^1.4.0
  internet_connection_checker_plus: ^3.1.1

  # Storage
  flutter_secure_storage: ^10.3.1

  # Model
  json_annotation: ^4.12.0
  freezed_annotation: ^3.1.0
  equatable: ^2.1.0

  # Dependecny Injection
  get_it: ^9.2.1
  injectable: ^3.0.0

  # Utilities
  intl: ^0.20.3

  # UI
  cached_network_image: ^3.4.1
  flutter_svg: ^2.3.0
  fl_chart: ^1.2.0
  lottie: ^3.5.1
  skeletonizer: ^2.1.3
  google_fonts: ^8.1.0
  shimmer: ^3.0.0
  flutter_slidable: ^4.0.3
  badges: ^3.2.0
  
  # Media
  image_picker: ^1.2.3
  camera: ^0.12.0+1
  video_player: ^2.11.1

  # QR Code
  mobile_scanner: ^7.2.0
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.4

  # Connectivity
  connectivity_plus: ^7.2.0

  # Smart Hotel
  wakelock_plus: ^1.6.1
  web_socket_channel: ^3.0.3

  # Printing & PDF
  syncfusion_flutter_pdfviewer: ^34.1.30
  pdf: ^3.13.0
  printing: ^5.15.0
  esc_pos_printer_plus: ^0.1.1

  # Web
  webview_flutter: ^4.14.1
  url_launcher: ^6.3.2
  share_plus: ^13.2.0

  # Notification
  flutter_local_notifications: ^22.0.1
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1

  # Others
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  syncfusion_flutter_datagrid: ^34.1.30
  device_info_plus: ^13.2.0
  package_info_plus: ^10.2.0
  permission_handler: ^12.0.3
  logger: ^2.7.0
  uuid: ^4.5.3
  encrypt: ^5.0.3
  screen_brightness: ^2.1.11
  flutter_kiosk_mode: ^0.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.5
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^4.0.4
  build_runner: ^2.15.1


  flutter_lints: ^6.0.0



flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/icons/icon_logo.png"

  adaptive_icon_background: "#222A1F"
  adaptive_icon_foreground: "assets/icons/icon_logo.png"

  remove_alpha_ios: true


flutter:

  uses-material-design: true


assets:
    - assets/images/
    - assets/icons/
    - assets/splash