@props([
    'src' => '',
    'alt' => '',
    'sizes' => '100vw',
    'widths' => [480, 768, 1080, 1440],
])
@php
    // Emit a <picture> so the BROWSER chooses the .webp directly — no server
    // content-negotiation needed (works on nginx, Apache, or a CDN alike).
    // Width variants + .webp siblings are generated by `php artisan images:webp`.
    $isRaster = $src && preg_match('/\.(jpe?g|png)$/i', $src);

    $exists = fn ($url) => ($p = parse_url($url, PHP_URL_PATH)) && is_file(public_path(ltrim(urldecode($p), '/')));
    $toWebp = fn ($url) => preg_replace('/\.(?:jpe?g|png)$/i', '.webp', $url);

    $jpgSrcset = [];
    $webpSrcset = [];
    if ($isRaster) {
        foreach ((array) $widths as $w) {
            $variant = preg_replace('/(\.(?:jpe?g|png))$/i', "-{$w}\$1", $src);
            if ($exists($variant)) {
                $jpgSrcset[] = $variant.' '.$w.'w';
                if ($exists($toWebp($variant))) {
                    $webpSrcset[] = $toWebp($variant).' '.$w.'w';
                }
            }
        }
    }

    // Full-size .webp sibling (used when no width variants exist on disk).
    $baseWebp = $isRaster ? $toWebp($src) : null;
    $hasBaseWebp = $baseWebp && $exists($baseWebp);
@endphp
@if ($isRaster && ($webpSrcset || $hasBaseWebp))
    {{-- display:contents so the wrapper adds no box — the <img> keeps its own layout/classes. --}}
    <picture class="contents">
        <source type="image/webp"
                srcset="{{ $webpSrcset ? implode(', ', $webpSrcset) : $baseWebp }}"
                @if ($webpSrcset) sizes="{{ $sizes }}" @endif>
        <img src="{{ $src }}" alt="{{ $alt }}"
             @if ($jpgSrcset) srcset="{{ implode(', ', $jpgSrcset) }}" sizes="{{ $sizes }}" @endif
             {{ $attributes }}>
    </picture>
@else
    <img src="{{ $src }}" alt="{{ $alt }}"
         @if ($jpgSrcset) srcset="{{ implode(', ', $jpgSrcset) }}" sizes="{{ $sizes }}" @endif
         {{ $attributes }}>
@endif
